GET http://localhost:3000/api/v1/tasks/ HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/api/v1/tasks/swdawdsaw HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3000/api/v1/tasks/ HTTP/1.1
Content-Type: application/json

###

PATCH   http://localhost:3000/api/v1/tasks/dawdikjaaw HTTP/1.1
Content-Type: application/json

###

DELETE   http://localhost:3000/api/v1/tasks/dawdikjaaw HTTP/1.1
Content-Type: application/json

###